In [1]:
import numpy as np

In [ ]:
import glob

In [2]:
import math as m

In [3]:
import scipy.stats

## 1

In [7]:
x = np.zeros(10)
x[4] = 1
print(x)

[ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]


## 2

In [10]:
v = np.arange(10,50,1)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3

In [11]:
def reverse(vector):
    """return a 1D vector with the elements reversed

Input
-----
    x: 1D array

Output
------
    res: 1D array, with the elements of `x` reversed"""
    return vector[::-1]

a = np.arange(10)
print(a)
b = reverse(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## 4

In [19]:
d = [1,2,0,0,4,0]
e = np.array(d)

In [20]:
def find_nonzero(array):
    """return the indices of non-zero elements of an array.

Input:      x:  array
Output:     indices: array of integer indices"""
    for element in array:
        return(np.where(element!=0))
find_nonzero(e)

(array([0]),)

## 5

In [32]:
x = np.random.normal(0.5,0.1,(3,3,3))
x

array([[[ 0.45854994,  0.34607814,  0.43551883],
        [ 0.46736039,  0.62395194,  0.50639255],
        [ 0.58046183,  0.5256454 ,  0.59347173]],

       [[ 0.48739813,  0.70202256,  0.37563065],
        [ 0.4596888 ,  0.55167787,  0.54224351],
        [ 0.50681852,  0.54601109,  0.43695048]],

       [[ 0.33780622,  0.45925828,  0.36133905],
        [ 0.44357471,  0.5701879 ,  0.49316206],
        [ 0.53148336,  0.60033202,  0.44088636]]])

## 6

In [37]:
random_array = np.random.rand(10,10)
print(random_array)
print(random_array.min(axis=0)[2])
print(random_array.max(axis=1)[4])

[[ 0.71317991  0.52085095  0.56317346  0.32308414  0.16410426  0.48535508
   0.08777766  0.10705626  0.17243968  0.15797685]
 [ 0.43800711  0.86748068  0.09647915  0.15125605  0.40293203  0.27503821
   0.98377313  0.94879504  0.75455983  0.40240164]
 [ 0.0945123   0.25008676  0.1992181   0.49923155  0.08552212  0.80697346
   0.95880758  0.00697489  0.61246326  0.88838025]
 [ 0.8577425   0.73993479  0.88879958  0.85055425  0.27772536  0.22218489
   0.55480107  0.10642382  0.95930926  0.28849862]
 [ 0.12718382  0.59293999  0.84357934  0.45345802  0.33680423  0.01473821
   0.09455254  0.41531244  0.1787214   0.79112556]
 [ 0.23131075  0.34198691  0.60886769  0.32480281  0.8478939   0.76980933
   0.95891578  0.76216022  0.44174143  0.24424009]
 [ 0.41801063  0.71792353  0.21464475  0.7131966   0.49574283  0.74462168
   0.60394056  0.02530471  0.44414624  0.71721391]
 [ 0.80730617  0.49009671  0.12222381  0.44440563  0.45464469  0.91343714
   0.14058925  0.98280066  0.74515263  0.57083801]


## 7

In [50]:
np.linspace(0.05,1,10,False)

array([ 0.05 ,  0.145,  0.24 ,  0.335,  0.43 ,  0.525,  0.62 ,  0.715,
        0.81 ,  0.905])

## 8

In [53]:
random_vec = np.random.rand(10)
print(random_vec)
np.sort(random_vec)

[ 0.15443722  0.85711933  0.35336949  0.8849256   0.15435979  0.51889542
  0.92614858  0.26657783  0.29335747  0.73358143]


array([ 0.15435979,  0.15443722,  0.26657783,  0.29335747,  0.35336949,
        0.51889542,  0.73358143,  0.85711933,  0.8849256 ,  0.92614858])

## 9

In [55]:
def is_equal(a1,a2):
    """return True if two arrays are the same shape and all the elements are equal.

Inputs:
    A, B:  array
Output:
    Bool:  True if A and B have the same shape and identical elements."""
    while a1.shape == a2.shape: # Check if shapes are the same
        if a1.sum() == a2.sum(): # Check if elements are the same by comparing sums of the elements
            return(True)
    else:
        return(False)
# The tricky part here was how to determine if elements are equal without using another function (I found multiple)

## 10

In [13]:
"""Calculate mean for each row in a matrix, and then subtract that mean
from the respective rows"""

x = np.arange(6).reshape(3,2) # Shape is (3,2)
mean1 = x.mean(axis=1) # Shape is (3,); cannot broadcast with this
y = x.T # Transpose x, now (2,3)
z = np.subtract(y,mean1) # Subtract mean (3,) from y (2,3)
# Following broadcasting rules,can now to do above subtraction
print(z.T) # Transpose the result
# Final product is now element in each row minus the mean of that row

[[-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]]


## 11

In [4]:
a = np.random.rand(5,5,3)
b = np.random.rand(5,5)
c = np.random.rand(3,5,5)
b2 = b[:,:,np.newaxis] # Create a singleton axis
print(b2.shape) # Shape of array is now (5,5,1)
sol1 = a*b2 # (5,5,3)*(5,5,1)
sol2 = b*c # (5,5)*(3,5,5)
print(sol1.shape)
print(sol2.shape)

(5, 5, 1)
(5, 5, 3)
(3, 5, 5)


## 12

In [3]:
z = np.arange(1,15,1)
z1 = z[:11, np.newaxis]
z2 = np.abs(z1+[0,1,2,3])
print(z2)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [14]:
z2 = np.abs(((np.arange(1,15,1))[:11, np.newaxis])+[0,1,2,3])
print(z2)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


## 13

In [ ]:
def cart2polar(x,y):
    """Convert Cartesian coordinates (N,2) to polar coordintes (r,theta)"""
    r = np.sqrt(x**2 + y**2)
    theta = np.arctan2(y,x)
    return(r,theta)

## 14

## 15

In [30]:
def calculate(a, b):
    """Do some calculations
    
    Take in two arrays, subtract 1/4 of the [:2,:] elements from the elements themselves.
    Then multiply with array b and return the result.
    
    Inputs:
        a: input array, shape [MxN]
        b: input array, shape [M]
    
    Returns:
        resultant array
    """
# a[:2,:] --> [row,column] therefore, == first two rows
# aa =/4 Results in 1/4, so 0.25, which is THEN subtracted from itself
    # Therefore, we get [0,0][0,0][3,3]
# Array b is not altered during this calculation
# we want [2.25,2.25][2.25,2.25][3,3] so... 

    aa = a[:2,:]
    aa -= (aa/4) # Equivalent to aa = aa - (aa/4); now we only subtract 0.25 to get 0.75 in the first two rows
    g = a.T # b.shape is (3,); a.shape is (3,2) so we transpose and g.shape is (2,3) 


    return (g*b).T # (g*b).shape would be (2,3), so we ensure result is transposed
    
a = np.ones((3, 2))
b = np.ones(3)*3
res = calculate(a, b)

assert (res == np.array([[ 2.25,  2.25],[ 2.25,  2.25],[ 3., 3.]])).all()

## 16

In [7]:
burl = np.loadtxt('burl1h2010.txt', comments='#')
wind_dir = burl[:,5] #1D array for wind direction
wind_spd = burl[:,6] #1D array for wind speed
print(wind_dir) # degT
print(wind_spd) # m/s
# u = (wind_spd)*(cos(deg)) where deg is wind_dir
# v = (wind_spd)*(sin(deg)) where deg is wind_dir

[ 134.  123.  130. ...,  147.  152.  150.]
[  3.    3.6   3.3 ...,  11.4  11.9  10.2]


In [12]:
def w_vector(vdir,vspd):
    """Take in vector and return components.

Inputs:
    vdir: vector direction in degrees
    vspd: vector magnitude

Returns:
    u: x component of vector
    v: y component of vector"""
# Have vdir and vspd been set yet as arrays?
    
    u = vspd*(np.cos(vdir))
    v = vspd*(np.sin(vdir))
    print(u)
    print(v)

w_vector(wind_dir,wind_spd)

[-1.39148661 -3.19668806 -1.21206139 ..., -9.04175518  4.27262701
  7.13235823]
[  2.65777445  -1.65565257  -3.06934964 ...,   6.94310185  11.10651423
  -7.29173958]


## 17

## 18